[build]
  command = "npm ci && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  # Leave NEXT_PUBLIC_BASE_PATH empty for Netlify
  NEXT_PUBLIC_BASE_PATH = ""
  # Disable Netlify Next.js runtime (we are using static export)
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

